---
title: "recreate_figs_1_2"
author: "Natalie Davidson"
date: "8/15/2021"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = c('png', 'pdf'))

require("data.table")
require("here")
require("ggplot2")
require("dplyr")
require("ggpubr")
require("networkD3")
require("dplyr")
theme_set(theme_pubr())

proj_dir = here()

set.seed(5)


```
# Make Sankey Diagram

Show how clusters are broken up across datasets.
To do this we will use a sankey diagram.

## First get file paths

```{r get_sankey_file, fig.align='center', fig.width=15, fig.height=15, echo=TRUE, warning=FALSE, message=F}

sankey_file = file.path(proj_dir, 
                    "/data/way_pipeline_results_10removed_NeoRemoved_inclWhites/2.Clustering_DiffExprs-Tables-ClusterMembership/FullClusterMembership.csv")

sankey_df = data.frame(fread(sankey_file))


```


## Plotting method

```{r get_sankey_fig, fig.align='center', fig.width=15, fig.height=15, echo=TRUE, warning=FALSE, message=F}

get_sankey_df <- function(sankey_df, dataset){
    
    curr_df = subset(sankey_df, Dataset == dataset)
    curr_df = curr_df[,c("ClusterK2_kmeans", "ClusterK3_kmeans", "ClusterK4_kmeans")]
    curr_df$ClusterK2_kmeans = paste("k=2, cluster", curr_df$ClusterK2_kmeans, sep=" ")
    curr_df$ClusterK3_kmeans = paste("k=3, cluster", curr_df$ClusterK3_kmeans, sep=" ")
    curr_df$ClusterK4_kmeans = paste("k=4, cluster", curr_df$ClusterK4_kmeans, sep=" ")
    
    # additional text
    k2 = as.data.frame(table(curr_df$ClusterK2_kmeans))
    k3 = as.data.frame(table(curr_df$ClusterK3_kmeans))
    k4 = as.data.frame(table(curr_df$ClusterK4_kmeans))
    text_df <- rbind(k2, k3)
    text_df <- rbind(text_df, k4)
    colnames(text_df) = c("source", "source_freq")
    s_text_df = text_df
    t_text_df = text_df
    colnames(t_text_df) = c("target", "target_freq")

    
    # make first pass
    flow1_df = as.data.frame(table(curr_df[1:2]))
    colnames(flow1_df) = c("source", "target", "value")
    flow1_df = merge(flow1_df, s_text_df)
    flow1_df$source = paste0(flow1_df$source, "\nN=", flow1_df$source_freq)
    flow1_df = flow1_df[,c("source", "target", "value")]
    flow1_df = merge(flow1_df, t_text_df)
    flow1_df$target = paste0(flow1_df$target, "\nN=", flow1_df$target_freq)

    # make second pass
    flow2_df = as.data.frame(table(curr_df[2:3]))
    colnames(flow2_df) = c("source", "target", "value")
    flow2_df = merge(flow2_df, s_text_df)
    flow2_df$source = paste0(flow2_df$source, "\nN=", flow2_df$source_freq)
    flow2_df = flow2_df[,c("source", "target", "value")]
    flow2_df = merge(flow2_df, t_text_df)
    flow2_df$target = paste0(flow2_df$target, "\nN=", flow2_df$target_freq)

    # combine
    links_df = rbind(flow1_df, flow2_df)

    # make nodes
    nodes_df <- data.frame(name=c(as.character(links_df$source), 
                               as.character(links_df$target)) %>% unique())
    

    
    # make numeric ID
    links_df$IDsource <- match(links_df$source, nodes_df$name)-1 
    links_df$IDtarget <- match(links_df$target, nodes_df$name)-1
    
    return(list(links=links_df, nodes=nodes_df, text=text_df))
    
}

plot_sankey <- function(links_df, nodes_df){
    
    p <- sankeyNetwork(Links = links_df, Nodes = nodes_df,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              sinksRight=FALSE, iterations=0, fontSize = 24, width=1000, height = 300)
    
    return(p)
}


```

## Now make proportions plot

```{r plot_aaces_sankey, fig.align='center', fig.width=100, fig.height=50, echo=TRUE, warning=FALSE, message=F}

stable_IDS_W_samp = paste0("Sample_", schW_consensus_way)
stable_IDS_B_samp = paste0("Sample_", schB_consensus_way)
stable_ids = c(stable_IDS_W_samp, stable_IDS_B_samp, tcga_consensus_way,
            mayo_consensus_way, tothill_consensus_way, yoshihara_consensus_way)
sankey_df_stable = subset(sankey_df, V1 %in% stable_ids)
#sankey_df_stable = sankey_df

gg1 = ggplot(data=filter(sankey_df_stable, Dataset != "aaces.eset"), aes(x=ClusterK4_kmeans, fill=factor(ClusterK3_kmeans))) +
    geom_bar(position="fill") + 
    facet_wrap(~ Dataset)
gg1

gg2 = ggplot(data=filter(sankey_df_stable, Dataset != "aaces.eset"), aes(x=ClusterK3_kmeans, fill=factor(ClusterK2_kmeans))) +
    geom_bar(position="fill") + 
    facet_wrap(~ Dataset)
gg2

sankey_df2 = sankey_df_stable
sankey_df2$all_clust = paste(sankey_df_stable$ClusterK2_kmeans, sankey_df_stable$ClusterK3_kmeans, sankey_df_stable$ClusterK4_kmeans, sep="_")

```

## Now make the sankey plot

```{r plot_aaces_sankey, fig.align='center', fig.width=100, fig.height=50, echo=TRUE, warning=FALSE, message=F}

aaces_network = get_sankey_df(sankey_df, dataset="aaces.rnaseq.eset")
aaces_plot = plot_sankey(aaces_network[["links"]], aaces_network[["nodes"]])
aaces_plot


```

```{r plot_aaces_sankey_W, fig.align='center', fig.width=100, fig.height=50, echo=TRUE, warning=FALSE, message=F}


aaces_network = get_sankey_df(sankey_df_stable, dataset="aaces.white.rnaseq.eset")
aaces_plot = plot_sankey(aaces_network[["links"]], aaces_network[["nodes"]])
aaces_plot


```


## Now for each dataset make the sankey plot

```{r plot_tcga_sankey, fig.align='center', fig.width=15, fig.height=15, echo=TRUE, warning=FALSE, message=F}

tcga_network = get_sankey_df(sankey_df, dataset="TCGA")
tcga_plot = plot_sankey(tcga_network[["links"]], tcga_network[["nodes"]])
tcga_plot



```

```{r plot_mayo_sankey, fig.align='center', fig.width=15, fig.height=15, echo=TRUE, warning=FALSE, message=F}

mayo_network = get_sankey_df(sankey_df, dataset="mayo.eset")
mayo_plot = plot_sankey(mayo_network[["links"]], mayo_network[["nodes"]])
mayo_plot



```

```{r plot_tothill_sankey, fig.align='center', fig.width=15, fig.height=15, echo=TRUE, warning=FALSE, message=F}

tothill_network = get_sankey_df(sankey_df, dataset="Tothill")
tothill_plot = plot_sankey(tothill_network[["links"]], tothill_network[["nodes"]])
tothill_plot


```

```{r plot_yoshihara_sankey, fig.align='center', fig.width=15, fig.height=15, echo=TRUE, warning=FALSE, message=F}

yoshihara_network = get_sankey_df(sankey_df, dataset="Yoshihara")
yoshihara_plot = plot_sankey(yoshihara_network[["links"]], yoshihara_network[["nodes"]])
yoshihara_plot


```


